### ISSUE TITLE
Expose a way to call timer.clear()

### ISSUE THREAD

**Issue by mnkhouri** [oskosk/node-polling-to-event#6]
There currently isn't an explicit way stop the polling completely, without calling `emitter.interval.clear()`. The `pause()` does prevent the user's function from being called, but there is a still a tick firing on every polling interval. Could you explicitly expose a method to call pauseable's `timer.clear()`?

Maybe:

```
pollingtoevent.prototype.clear = function() {
  debug("Clearing interval");
  this.interval.clear();
}
```

**Comment by vincent-tr** [comment]
Any new on this ?

**Comment by vincent-tr** [comment]
Thanks :)

**Comment by oskosk** [comment]
Sorry @vincent-tr . Thanks for the PR. I bumped version and republished in npm. Sorry again for the loooooong delay

**Comment by oskosk** [comment]
Added in #7

**Comment by vincent-tr** [comment]
Thank you very much.
No problem for the long delay :)
